keys:
  - &eren age1u4jt98vv0jv57jeca476pev3nkxcetkgze7d36hfsf6r04sddeds5a7qeg
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
    - age:
      - *eren
  - path_regex: ^hosts/eren/secrets.yaml$
    key_groups:
    - age:
      - *eren
